
workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 20
    environment:
      flutter: stable
      xcode: latest
      vars:
        ANDROID_BUILD_MODE: release
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
